# Generated by Django 5.0.3 on 2024-03-09 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=255)),
                ('mahsulot_kodi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xomashyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xomashyo_nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Omborxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.IntegerField()),
                ('price', models.FloatField()),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.xomashyo')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot_Xomashyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.mahsulot')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.xomashyo')),
            ],
        ),
    ]
