# Generated by Django 5.0.3 on 2024-03-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0002_alter_mahsulot_xomashyo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot_xomashyo',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
